
all :
	cd src; $(MAKE)
	cd tests; $(MAKE)
	cd validator; $(MAKE)
	cd simpleserver; $(MAKE)

clean :
	rm -f core
	cd src; $(MAKE) clean
	cd tests; $(MAKE) clean
	cd validator; $(MAKE) clean
	cd simpleserver; $(MAKE) clean
